/**
 * Fallback mock data — used when Yahoo Finance or the API route fails.
 * Shape must match AnalysisResult from @/types/analysis.
 */
import type { AnalysisResult } from "@/types/analysis";

export const mockTickerData: Record<string, AnalysisResult> = {
  NVDA: {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    price: "$132.45",
    change: "+$4.12",
    changePercent: "+3.2%",
    isPositive: true,
    recommendation: "STRONG BUY",
    confidence: 91,
    bullConfidence: 94,
    bearConfidence: 41,
    bullArgs: [
      "Unprecedented demand for Hopper architecture GPUs continues to outstrip supply across every major cloud provider.",
      "CUDA software ecosystem creates a nearly insurmountable moat — 4M+ developers locked into the platform.",
      "Data center revenue is accelerating with massive hyperscaler capex commitments exceeding $200B collectively.",
    ],
    bearArgs: [
      "Gross margins may have peaked as TSMC raises wafer prices by 8% and AMD MI300X gains traction.",
      "Over-reliance on top 4 hyperscaler customers creates concentrated revenue risk — 60% of total revenue.",
      "Geopolitical export controls risk cutting off $8B+ in emerging market AI revenue streams.",
    ],
    judgeSummary:
      "NVDA's data center dominance is clear, but its 52-week position near highs and elevated beta suggest the market has already priced in significant optimism. The bull case rests on sustained capex from hyperscalers; the bear case centres on margin pressure and geopolitical exposure.",
    marketStats: {
      marketCap: "$3.28T",
      range: "$47 – $153",
      volume: "312M",
      beta: "1.68",
      instOwnership: "65.8%",
      sector: "Technology",
    },
    scoreBreakdown: {
      momentum: 4.8,
      marketCapStability: 5.0,
      dailyTrend: 4.0,
      volatility: 2.0,
      sectorStrength: 4.5,
      total: 91,
    },
    dataSource: "fallback",
    lastUpdated: Date.now(),
  },
  AAPL: {
    symbol: "AAPL",
    name: "Apple Inc.",
    price: "$198.11",
    change: "-$1.20",
    changePercent: "-0.6%",
    isPositive: false,
    recommendation: "HOLD",
    confidence: 65,
    bullConfidence: 55,
    bearConfidence: 58,
    bullArgs: [
      "Services revenue continues to grow double-digits, offering high-margin recurring income.",
      "Integration of local AI (Apple Intelligence) is expected to drive a massive iPhone upgrade supercycle.",
      "Unrivalled balance sheet with $160B in cash provides immense flexibility for share buybacks.",
    ],
    bearArgs: [
      "Hardware sales in China are slowing significantly due to domestic competition and regulatory pressure.",
      "App Store regulatory crackdowns in the EU threaten the 30% take rate, a key margin driver.",
      "Valuation is historically stretched compared to projected single-digit earnings growth.",
    ],
    judgeSummary:
      "AAPL sits near the middle of its 52-week range and trades at a premium multiple relative to its modest growth outlook. Services momentum is the primary bull catalyst, while China risk and EU regulation remain material overhangs.",
    marketStats: {
      marketCap: "$3.05T",
      range: "$165 – $199",
      volume: "58M",
      beta: "1.24",
      instOwnership: "61.2%",
      sector: "Technology",
    },
    scoreBreakdown: {
      momentum: 3.2,
      marketCapStability: 5.0,
      dailyTrend: 2.5,
      volatility: 3.0,
      sectorStrength: 4.5,
      total: 65,
    },
    dataSource: "fallback",
    lastUpdated: Date.now(),
  },
  TSLA: {
    symbol: "TSLA",
    name: "Tesla Inc.",
    price: "$248.90",
    change: "+$12.30",
    changePercent: "+5.1%",
    isPositive: true,
    recommendation: "BUY",
    confidence: 78,
    bullConfidence: 82,
    bearConfidence: 45,
    bullArgs: [
      "FSD v12 is showing exponential improvement, nearing robotaxi viability at scale.",
      "Energy storage deployments grew 150% YoY, becoming a highly profitable secondary business.",
      "Manufacturing cost per vehicle continues to drop, allowing Tesla to win margin wars against legacy auto.",
    ],
    bearArgs: [
      "EV demand globally is cooling, leading to persistent inventory build-up and aggressive price cuts.",
      "Cybertruck production ramp is burning significant capital and facing manufacturing hurdles.",
      "Key executive departures and unpredictable leadership create heightened operational risk.",
    ],
    judgeSummary:
      "TSLA's strong daily momentum and improving 52-week positioning reflect renewed optimism around FSD and energy storage. However, its high beta of 2.31 signals the market prices in significant uncertainty on both upside and downside.",
    marketStats: {
      marketCap: "$794B",
      range: "$138 – $299",
      volume: "125M",
      beta: "2.31",
      instOwnership: "43.5%",
      sector: "Consumer Cyclical",
    },
    scoreBreakdown: {
      momentum: 3.9,
      marketCapStability: 4.0,
      dailyTrend: 5.0,
      volatility: 1.0,
      sectorStrength: 3.8,
      total: 78,
    },
    dataSource: "fallback",
    lastUpdated: Date.now(),
  },
  JPM: {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    price: "$201.90",
    change: "+$0.45",
    changePercent: "+0.2%",
    isPositive: true,
    recommendation: "STRONG BUY",
    confidence: 88,
    bullConfidence: 90,
    bearConfidence: 30,
    bullArgs: [
      "Net interest income remains strong even as rate cut expectations get pushed out further.",
      "Investment banking fees are recovering rapidly with a resurgence in M&A and IPO activity.",
      "Fortress balance sheet allows the bank to continuously acquire distressed assets at steep discounts.",
    ],
    bearArgs: [
      "Commercial real estate exposure, while manageable, remains a drag on credit provisioning.",
      "Consumer defaults and credit card charge-offs are slowly creeping back to pre-pandemic levels.",
      "Heightened capital requirements (Basel III endgame) may restrict future dividend growth.",
    ],
    judgeSummary:
      "JPM's low beta and mega-cap stability make it one of the most dependable risk-adjusted holdings in financial services. Near its 52-week high with steady positive daily momentum, the data supports a constructive view, tempered only by macro rate sensitivity.",
    marketStats: {
      marketCap: "$582B",
      range: "$135 – $205",
      volume: "9.2M",
      beta: "1.12",
      instOwnership: "72.4%",
      sector: "Financial Services",
    },
    scoreBreakdown: {
      momentum: 4.7,
      marketCapStability: 5.0,
      dailyTrend: 3.0,
      volatility: 3.5,
      sectorStrength: 3.5,
      total: 88,
    },
    dataSource: "fallback",
    lastUpdated: Date.now(),
  },
};
